### PR TITLE
Automatically make channel for year-day

### LINKED ISSUE #26: Automatically/Dynamically propagate day channels into category of choice.
Automatically make the channels in a category.
Category can be set using the command interface, In which channels with name `{year}-{day}` will be made
- #13

### PR DESCRIPTION
**Pull request by daanbreur**
- Closes #26

### CODE REVIEW

**Comment by daanbreur** [comment]
@TrojanerHD

**Comment by daanbreur** [comment]
This is untested and not sure if it will work
According to https://discord.js.org/docs#/docs/main/stable/class/CategoryChannel?scrollTo=createChannel it should

**Comment by LeMoonStar** [comment]
Could you add a ( Closes #26 ) to the title or description of the pull request, well, if I can't add it by having it in this comment that is.

**Comment by LeMoonStar** [comment]
> This is untested and not sure if it will work
> According to https://discord.js.org/docs#/docs/main/stable/class/CategoryChannel?scrollTo=createChannel it should

Also, the link is broken, here is the working one:
https://discord.js.org/#/docs/main/stable/class/CategoryChannel?scrollTo=createChannel

**Comment by daanbreur** [comment]
Both links work for me

**Comment by LeMoonStar** [comment]
> Both links work for me

Interesting, on mobile the first link doesn't work for me, but on my PC it does.

**Comment by TrojanerHD** [comment]
> Could you add a ( Closes #26 ) to the title or description of the pull request? Well, if I can't add it by having it in this comment that is.

Apparently, adding it to the title doesn't work. I changed the initial comment and the title and now it works

**Comment by LeMoonStar** [comment]
> > Could you add a ( Closes #26 ) to the title or description of the pull request? Well, if I can't add it by having it in this comment that is.
> 
> Apparently, adding it to the title doesn't work. I changed the initial comment and the title and now it works

Interesting

**Review by TrojanerHD — APPROVED** [review]

**Pull request merged**
